language: python
python:
- "3.5"
- "3.6"
- "3.7"
- "3.8"
- "3.8-dev"
before_install:
- make install
services:
- mongodb
script:
- make test
after_success:
- codecov
env:
  global:
  - secure: I7tUPhoe9SdWQ1gigt6z1bl1mr52KDZwReZTa9DQnKqVBziMzfIcK+R5SSN4zAOucFgRg5jyOWdGxud3vSQ+ZhAiyHJIi+ZLtsnGIez5qm3NVMRlnOE2infRwWsMTQwFWpIMuz1vj+k1s0j8Xr1TrYd5KSrMnGWPt255G5jDnedSQWJ5hmQWSf2DqhLLl3pj9kEcktLwN+G8iBUBViSFRn/jVb9rmqCY95BznlTLWAcK+dz74Pfr9FcugJp7XVpOE51ZskEUX3Lg2tbZYHc/hVjPcgLGM7vRD9305DooGIW7oZi2g2U3faPIrbDe+V9eLsjhyO/7lKagQeO7DW9Yc2VYZ29/IUQcAOmcBBrJqZmDOBg+AwnnNzzHFxH+ZH4cxWmjPphnTRdAifqZnfzpOjiuRubupsSyTQC+0zylkUTM4No+yoQxBfqeOwpjQa728jDAGOJsJmYjIcS9VdQcX8VNCQxTUru1c81XfZjakgfSDprACuk2hfi56VFFERlDqAEz2VMqnYEd4ZxwPbkxeHMrYqmYraNt75ejnuZJmJdeyRKYH+cOEk4ci5ohpmkcu1rLNFqBAsUTaonCnlGj3EyCGXfmIqBG3Tll5z5zAkxzvQbjr0x50cI4CWkvCoe9SLXVRKfFA6YgZOzSu8Lc3BG74YXv/R5nJS7lCxNlvoU=
  - secure: tvZOq+HH3MNbx0vqygdNVACDRC9/V93CWBmd4CeueX5UPx3x4E9FQgT6lzFr6wWjXO3Z2nCWOUwimLCLGXvwLrfdbsT9w7Z7J6GZ4ZtECzgwpLJWIX34RiFS29fEBZpzL9QQck6zukZG/zh4VJttNXVH8kAkUTbErzDaohMot6c0CBE+zCTEE1rY/Ng7u1GqcHWsyl07iIOKi/lMMNdy67zNaxv9Wv1uyRdRiPRVcgRSnO0LTqkgccvShauUvHOVzYqevPWTFOZFCrEg9e2RdeQOlwOJS4HylD0Ripb47UUo41P9kpnDrHfmZvcfOP8LW7UOxQSpn7xHMPr6Y9KELJ+cLlWYsEKSJjjoksaNcgEAKicwMf7Bsd7i34ZDpQ3gUJLYkkCrDOpwlPhOfjZU8LAfCJzhl/x2Njrkm5liMrV8OGYZu0eUZxxo5z8Iq61lwFExgZtlvBwT2asIBPLkEA0qy3Z5RrYgexXLotrhOhcpW7hdTRCcIvzL2nroXfBmmXpfAcEMCfC+AZzc8vyYaYezXl67gPRg/hAAa2DBPay3nfRYeI37sHD9q5o6E8FiQJf1AYVqi2M/Evn1Uk/9Ty9zLsm7tpOHIuwiyt/jFkvX6SqANyyaEiXPmrcGBqbgiA9WJa7/THkEBMQhUccjLzVNhX29d8XqL01ml5DMgfs=
  - secure: snCDJU5pUo8ntT7Bc+M+KfhRiRSj7hrlrOqyBNxievC2X4A4y7oAYLdcqXCv5dliaqXeVfHI9iIJNlODgKd02rVx5afj6/KkdxsBTskgrWMKQlyeu0w+hSzmtEiSj37hsjedR+Jxqo9/O+htYXoBNFGrQ15kpw1w9vW2gJ3nIu7TjHl2kbfxogQM3j+cFof0Guc4hEETS4QfIUR1Ie95vyk5W4GGUXv1tXm1nKfktBbDOOguIhzoZK1S9PSHJg0ZFgiWuDhL1itLanDYoAQFZRexyGYangMXomGoKlWp9ZJL97TkCOywMYzCKzE5BpFwANCorFaUt293Wdx2xmTYj1VBNv9m2Aw3sKExhWO4KpvZv3EzjsrspOxIyYc2W0zzg2HMHUnnEi0+j8Thw3kL3QzhW6q4jnG3PHv1LEUl9AbJ8cWTqQljQ4yPj2gI2QQ1jFA26amVgOLqAnsZwpLfYuiEfajvjQC3h6geu/oOdnwrOYMLW2W4VD5kbJU2QFaeOVo6zITIyWQEGYjtkVCZ5wEP8SIXhy35R1H6OC9v9w5TGlS2+1MsVl33LTw99/2xr1DORw4lhkb9IIjVnlVKprD8Ir4B0q4Ok8dfhJ3DZ63GIjmbm+DiTxEP+PMD33jhM2hIvaF7mPr1f/Ae5lZJoHniZRjkSW2SfGsR3aryY5o=
