version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Instalar un entorno virtual con python3
          command: pipenv install --three
      - run:
          name: Instalar dependencias
          command: pipenv run pip install -r requirements.txt
      - run:
          name: Ejecutar tests
          command: pipenv run python -m pytest tests/test_mascotas.py
      - run:
          name: Ejecutar test de cobertura
          command: pipenv run python -m pytest --cov=mascotas tests/
