version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Instalar las dependencias y crear el entorno virtual de Python.
          command: make install
      - run:
          name: Ejecutar los tests.
          command: make test
machine:
  services:
    - mongodb