- name: Instala las herramientas comunes a los microservicios de la máquina
        virtual así como git con el que descargaremos el repositorio de la asignatura.
  apt:
    pkg: ['git','python-setuptools','python3-pip', 'python3-docker']
    state: present
- name: Obtener el repositorio con los ficheros fuentes del proyecto.
  git:
    repo: https://github.com/lidiasm/ProyectoCC.git
    clone: yes
    dest: ProyectoCC
- name: Instalar las dependencias específicas del proyecto.
  pip:
    state: latest
    requirements: /home/lidia/ProyectoCC/requirements.txt
    executable: pip3